In [9]:
import pandas as pd
international_trade_data = pd.read_csv(r'./data/international_trade.csv')

In [11]:
international_trade_data = pd.read_csv(r'./data/international_trade.csv')
international_trade_data['품목명'].value_counts()

품목명
감귤                                                                               50
포포(papaw)[파파야(papaya)]                                                           50
레몬[시트러스 리몬(Citrus limon)ㆍ시트러스 리머늄(Citrus limonum)]                               50
그레이프프루트(grapefruit)와 포멜로(pomelo)                                                 50
오렌지                                                                              50
망고(mango)                                                                        50
파인애플                                                                             50
무화과                                                                              50
대추야자                                                                             50
사과                                                                               50
오이류(신선한 것이나 냉장한 것으로 한정한다)                                                        50
당근                                                                               50
배                                                                                50
결구(結球) 상추                                                                        50
양배추                                                                              50
방울다다기 양배추                                                                        50
꽃양배추와 브로콜리(broccoli)                                                             50
수박                                                                               49
망고스틴(mangosteen)                                                                 42
양파                                                                               42
자두                                                                               39
토마토(신선한 것이나 냉장한 것으로 한정한다)                                                        36
쪽파                                                                               36
콩[비그나(Vigna)속ㆍ파세러스(Phaseolus)속)]                                                 25
구아바(guava)                                                                       23
복숭아[넥터린(nectarine)을 포함한다]                                                        23
위트루프 치커리(Witloof chicory)[시코리엄 인티부스 변종 포리오섬(Cichorium intybus var. foliosum)]    22
신 체리[프루너스 체라서스(Prunus cerasus)]                                                  16
살구                                                                               15
방울토마토                                                                            14
샬롯(shallot)                                                                      14
완두[피섬 새티범(Pisum sativum)]                                                        11
참외                                                                               11
순무                                                                                6
Name: count, dtype: int64

In [12]:
# Mapping between item codes and item names in Korean
item_mapping = {
    'TG': '감귤',
    'BC': '꽃양배추와 브로콜리(broccoli)',
    'RD': '무',
    'CR': '당근',
    'CB': '양배추'
}

# Create a reverse mapping from item names to item codes
reverse_item_mapping = {v: k for k, v in item_mapping.items()}

# Replace item names in international_trade_data with item codes
international_trade_data['품목명'] = international_trade_data['품목명'].map(reverse_item_mapping)
international_trade_data = international_trade_data.dropna(subset=['품목명'])  # Drop rows with unmatched item names

international_trade_data

           기간 품목명   수출 중량  수출 금액    수입 중량  수입 금액  무역수지
3     2019-01  BC     160      1   638913    563  -562
5     2019-01  CB  184650     94   395802     90     4
8     2019-01  CR   23150     22  7466150   2955 -2934
17    2019-01  TG   58368    172        0      0   172
28    2019-02  BC     780      1   396870    399  -398
...       ...  ..     ...    ...      ...    ...   ...
1236  2023-01  TG   81509    269        0      0   269
1248  2023-02  BC      24      0   332640    352  -352
1250  2023-02  CB   13188     13   377456    104   -91
1253  2023-02  CR   22510     20  9260020   3758 -3737
1264  2023-02  TG    6895     34    27765     98   -64

[200 rows x 7 columns]